### PR TITLE
Add new config option to specify grant type that does not require client auth

### LINKED ISSUE #167: Code Auth Flow without client_secret in basic auth for SPA: Invalid credentials error
I am developing an SPA/mobile app and therefore I [cannot store the client secret](https://www.oauth.com/oauth2-servers/single-page-apps/) for security reasons.

Code Auth Flow is the only recommended way for SPAs and it seems it does not work witout a client secret which cannot be stored securely in a web app.

```
POST | http://localhost:3000/oauth2/token
grant_type=authorization_code
&client_id=82a0f410-3855-491e-a40c-1e0bb9b37e96
&redirect_uri=http%3A%2F%2Flocalhost%3A8100%2Fcallback
&code=381ae8e910b745df5ee19f5a92376aefe46bf020#
&code_verifier=Qn4wWh6I652XsBOGvPN2eBkroaZTRzjhHzGpebM8yPTvMS6mYIGrwSeLa9lODdWtT0KtCF3OwZN1YxktPbwFtTCDcWpS1ZtXfCKY9dLNCMwJbciUA7VuAGgxlisCjr8Q

```

I am seeing the following error in my log

```
Wed, 07 Oct 2020 13:57:31 GMT idm:oauth_controller Error  { invalid_client: Invalid client: cannot retrieve client credentials
fiware-keyrock |     at new InvalidClientError (/opt/fiware-idm/node_modules/oauth2-server/lib/errors/invalid-client-error.js:26:14)
fiware-keyrock |     at TokenHandler.getClientCredentials (/opt/fiware-idm/node_modules/oauth2-server/lib/handlers/token-handler.js:209:9)
fiware-keyrock |     at TokenHandler.getClient (/opt/fiware-idm/node_modules/oauth2-server/lib/handlers/token-handler.js:127:26)
fiware-keyrock |     at TokenHandler.<anonymous> (/opt/fiware-idm/node_modules/oauth2-server/lib/handlers/token-handler.js:96:19)
fiware-keyrock |     at TokenHandler.tryCatcher (/opt/fiware-idm/node_modules/oauth2-server/node_modules/bluebird/js/release/util.js:16:23)
fiware-keyrock |     at Promise._settlePromiseFromHandler (/opt/fiware-idm/node_modules/oauth2-server/node_modules/bluebird/js/release/promise.js:512:31)
fiware-keyrock |     at Promise._settlePromise (/opt/fiware-idm/node_modules/oauth2-server/node_modules/bluebird/js/release/promise.js:569:18)
fiware-keyrock |     at Promise._settlePromiseCtx (/opt/fiware-idm/node_modules/oauth2-server/node_modules/bluebird/js/release/promise.js:606:10)
fiware-keyrock |     at Async._drainQueue (/opt/fiware-idm/node_modules/oauth2-server/node_modules/bluebird/js/release/async.js:138:12)
fiware-keyrock |     at Async._drainQueues (/opt/fiware-idm/node_modules/oauth2-server/node_modules/bluebird/js/release/async.js:143:10)
fiware-keyrock |     at Immediate.Async.drainQueues [as _onImmediate] (/opt/fiware-idm/node_modules/oauth2-server/node_modules/bluebird/js/release/async.js:17:14)
fiware-keyrock |     at runCallback (timers.js:705:18)
fiware-keyrock |     at tryOnImmediate (timers.js:676:5)
fiware-keyrock |     at processImmediate (timers.js:658:5)
fiware-keyrock |   statusCode: 400,
fiware-keyrock |   status: 400,
fiware-keyrock |   code: 400,
fiware-keyrock |   message: 'Invalid client: cannot retrieve client credentials',
fiware-keyrock |   name: 'invalid_client' }
```

### PR DESCRIPTION
**Pull request by Siedlerchr**
oAuth2 server allows to configure for which grant types we need to authenticate the client. However, this option was not exposed in Keyrock and therefore it was not possible to do an Oauth2 Code flow without a client secret.
And for web apps or other public clients the client secret cannot be stored securely.
See here for details.
https://www.oauth.com/oauth2-servers/single-page-apps/

Example in docker compose:
`      - IDM_OAUTH_NOT_REQUIRE_CLIENT_AUTH_GRANT_TYPE=authorization_code`

Fixes #167

### CODE REVIEW

**Comment by apozohue10** [comment]
Hi @Siedlerchr 

Thank you very much for your contribution. You are right that storing the secret in a SPA is not secure. I think that the best solution to this issue is implementing the OAuth client types in Keyrock (public and confidential). What is your opinion?

**Comment by Siedlerchr** [comment]
I would agree that this could make sense. But not sure regarding the implementation, how to check for that during the token request

**Comment by Siedlerchr** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by apozohue10** [comment]
Thank you for your contribution. I will merge it.

**Pull request merged**
