### PR TITLE
Add support for mailgun

### PR DESCRIPTION
**Pull request by digigarlab**
Support [mailgun](https://www.mailgun.com) as transport for emails.

This introduces 3 new environment variables:
- `IDM_EMAIL_TRANSPORT`: `'smtp'` (default) or 'mailgun'
- `IDM_EMAIL_DOMAIN`: The domain in mailgun
- `IDM_MAILGUN_API_KEY`: The API key of the mailgun account associated with the domain.

If transport is set to `mailgun`, it will use the `nodemailer-mailgun-transport` to send the email, connecting to the mailgun API. Otherwise it will keep the current behaviour and connect through smtp to the local smtp server.

### CODE REVIEW

**Comment by digigarlab** [comment]
Any update on this? Are you willing to merge this?

**Comment by apozohue10** [comment]
Merged! Thank you for your contribution and sorry for the delay

**Comment by digigarlab** [comment]
No, problem :)
Do you plan to release a new version with this change soon? Do you have a roadmap or something?

**Comment by apozohue10** [comment]
We have a roadmap. It should be included on the root of this repo.
The new version with your change will be released by the end of August or in early September

**Pull request merged**
