### PR TITLE
Update CSS to avoid redirect

### PR DESCRIPTION
**Pull request by jason-fox**

### CODE REVIEW

**Comment by apozohue10** [comment]
Thanks @jason-fox!

**Comment by jason-fox** [comment]
@apozohue10  - Could you give ReadTheDocs a kick to refresh the CSS?

https://readthedocs.org/projects/fiware-idm/builds/

**Comment by apozohue10** [comment]
Done! Sorry I forgot it.

**Comment by jason-fox** [comment]
LGTM :smile: Thanks.

**Pull request merged**
