### PR TITLE
Feature/fiware service header as resource

### PR DESCRIPTION
**Pull request by SamuelTJackson**
We have always used authzforce to check the fiware-service header because we need the fiware-service header for multi-client capability. For us, however, it is easier to build this simple check into Keyrock than to use authzforce for it. If you are also interested to have this feature in the official version, here is the pr. 

I noticed that the endpoint '/user' does not require authentication. The pep-proxy still adds the authorization header (https://github.com/ging/fiware-pep-proxy/blob/master/lib/idm.js#L94)

This PR allows you to specify a fiware service header when creating permissions.
The api endpoint /user now accepts an additional query parameter 'fiware_service'

permission

### CODE REVIEW

**Comment by apozohue10** [comment]
Hi @SamuelTJackson,

many thanks for your contribution. We will study if it makes sense as there is a similar [functionality on the Pep Proxy](https://github.com/ging/fiware-pep-proxy/blob/master/config.js.template#L34). Would you mind to check if the PEP functionality would also solve your issue?

Regarding the pep-proxy authorization header, it is true that '/user' does not require authentication. However, in previous Keyrock releases it does. So we decided to maintain it.

**Comment by SamuelTJackson** [comment]
> Hi @SamuelTJackson,
> 
> many thanks for your contribution. We will study if it makes sense as there is a similar [functionality on the Pep Proxy](https://github.com/ging/fiware-pep-proxy/blob/master/config.js.template#L34). Would you mind to check if the PEP functionality would also solve your issue?
> 
> Regarding the pep-proxy authorization header, it is true that '/user' does not require authentication. However, in previous Keyrock releases it does. So we decided to maintain it.

Hey @apozohue10,
the functionality through the organizations can only partially help. For example, it is not possible to have one user who can access all data areas if he is not in all organizations. We have also replaced the Pep-proxies with Kong.

**Comment by apozohue10** [comment]
Hi @SamuelTJackson 

I think it would make sense if you can configure which header is going to be check. I mean, in your case is fiware-service but in other services would be interested on using different headers. Would you mind to edit the PR to make able Keyrock admins to configure their own header?

**Comment by SamuelTJackson** [comment]
Hey @apozohue10 
I can edit the PR but I'm not quite sure what do you mean. At this moment you are able to send the following request:
`https://keyrock.de/user?access_token=token&action=POST&resource=/v2/entities&app_id=asdfh2&fiware_service=custom`. So I could just change the wording. E.g. not calling the query parameter  `fiware-service` but `additional_header` or `additional_condition`(Changing it in the gui as well). So the user can send everything to this endpoint and it just get compared with the value saved in the permission. 
> Would you mind to edit the PR to make able Keyrock admins to configure their own header?

So what exactly do you mean with this? Keyrock admins should be able to change the explanation of the new field. So at the moment there is `Fiware Service Header` and `Use Fiware Service Header` as a static text. But the admin should be able to change this text to header name they want? E.g. `Custom-header Header` and `Use Custom-header Header`

**Comment by apozohue10** [comment]
Hi @SamuelTJackson 

> So I could just change the wording. E.g. not calling the query parameter fiware-service but additional_header or additional_condition(Changing it in the gui as well). So the user can send everything to this endpoint and it just get compared with the value saved in the permission.

Yes, this totally makes sense.

> So at the moment there is Fiware Service Header and Use Fiware Service Header as a static text. But the admin should be able to change this text to header name they want? E.g. Custom-header Header and Use Custom-header Header.

Mmmm I see, maybe this could be problematic with migrations. I think that the best option is to define a general static text, something like "Authorization Service Header" and "Use Authorization Service Header".

After doing that and merging the PR, I will create some documentation to explain how to use this feature (including as an example the fiware-service header). So people developing with FIWARE could easily understand how to do this.

**Comment by apozohue10** [comment]
Hi,

have you tried to run the tests using `npm run test:watch`? Maybe this helps to print some logs.

Also, you can try to run something like `npm run test:single test/integration/api/009-permissions.json` which runs a single test file and provide some debug traces.

**Comment by SamuelTJackson** [comment]
executing `npm run test:single test/integration/api/009-permissions.js`
```

> fiware-idm@7.9.0 test:single /home/samuel/Documents/fiware/fiware-idm
> DEBUG=idm:*,oauth2-server:* mocha "test/integration/api/009-permissions.js"

  idm:config *********************************************** +0ms
  idm:config WARNING: The current encryption keys match the defaults found in the plaintext +1ms
  idm:config          template file - please update for a production instance +0ms
  idm:config *********************************************** +0ms


  idm:config *********************************************** +1s
  idm:config WARNING: The current encryption keys match the defaults found in the plaintext +0ms
  idm:config          template file - please update for a production instance +0ms
  idm:config *********************************************** +0ms
  API - 9 - Permissions: 
sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules/sequelize/lib/sequelize.js:245:13
  idm:server Listening on port 3000 +747ms

    1) "before all" hook in "API - 9 - Permissions: "

  7) When creating a permission with resource+password+use_authorization_service_header and no authorization_service_header
  idm:api-authenticate  --> validate_token +30ms
  idm:api-authenticate Error: [object Object] +0ms
    ✓ should return a 400 Bad request

  8) When creating a permission with resource+password+authorization_service_header and no use_authorization_service_header
  idm:api-authenticate  --> validate_token +16ms
  idm:api-authenticate Error: [object Object] +0ms
    ✓ should return a 400 Bad request

  9) When creating a permission with authorization_service_header and xml in body
  idm:models Connection has been established successfully +3ms
  idm:api-authenticate  --> validate_token +2ms
  idm:api-authenticate Error: [object Object] +0ms
    ✓ should return a 400 Bad request

  10) When creating a permission with use_authorization_service_header and xml in body
  idm:api-authenticate  --> validate_token +3ms
  idm:api-authenticate Error: [object Object] +0ms
    ✓ should return a 400 Bad request

  11) When creating a permission with use_authorization_service_header equal false
  idm:api-authenticate  --> validate_token +3ms
  idm:api-authenticate Error: [object Object] +0ms
    2) should return a 201 OK


  4 passing (3s)
  2 failing

  1) API - 9 - Permissions: 
       "before all" hook in "API - 9 - Permissions: ":
     Uncaught TypeError: Cannot read property 'headers' of undefined
      at Request._callback (test/integration/api/009-permissions.js:37:24)
      at self.callback (node_modules/request/request.js:185:22)
      at Request.onRequestError (node_modules/request/request.js:877:8)
      at Socket.socketErrorListener (_http_client.js:469:9)
      at emitErrorNT (internal/streams/destroy.js:106:8)
      at emitErrorCloseNT (internal/streams/destroy.js:74:3)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)

  2) 11) When creating a permission with use_authorization_service_header equal false
       should return a 201 OK:

      Uncaught AssertionError: expected 400 to be 201
      + expected - actual

      -400
      +201
      
      at Assertion.fail (node_modules/should/cjs/should.js:275:17)
      at Assertion.value (node_modules/should/cjs/should.js:356:19)
      at Request._callback (test/integration/api/009-permissions.js:369:34)
      at Request.self.callback (node_modules/request/request.js:185:22)
      at Request.<anonymous> (node_modules/request/request.js:1154:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1076:12)
      at endReadableNT (_stream_readable.js:1252:12)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)
```
retrieving a token in the `before` function gives a 
```
Error: connect ECONNREFUSED 127.0.0.1:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1145:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 3000
}
```
But when I try to connect to keyrock through localhost:3000 it is reachable.  Maybe its a time problem. The tests are running before keyrock is up and ready.
Strange that `config_database` now works when I execute only one test. The idm_test database gets created and the data gets loaded. And at the end the `idm_test` database gets delted.

running` npm test`:
```
npm test                                                   

> fiware-idm@7.9.0 test /home/samuel/Documents/fiware/fiware-idm
> nyc --reporter=text mocha -- --recursive 'test/**/*.js' --reporter spec --timeout 3000 --ui bdd --exit



MySQL is up and running
-------------------|---------|----------|---------|---------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
File               | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s                                                                                                                                                        
-------------------|---------|----------|---------|---------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
All files          |   44.93 |    34.22 |      60 |   44.93 |                                                                                                                                                                          
 fiware-idm        |     100 |      100 |     100 |     100 |                                                                                                                                                                          
  config.js        |     100 |      100 |     100 |     100 |                                                                                                                                                                          
 fiware-idm/lib    |   38.71 |    33.51 |      60 |   38.71 |                                                                                                                                                                          
  configService.js |   38.71 |    33.51 |      60 |   38.71 | ...55-67,174-187,193,196,199,204-207,213,219,222,227-228,234-259,266,269,272,275,278,281,286-287,298,303-309,316-322,329,338,341,344,349-385,392,395,398,404,407,413-422 
```
no tests and no data gets loaded into the database. The database `idm_test` doesn't get deleted after.
and `npm run test:watch`
```
 npm run test:watch                                         

> fiware-idm@7.9.0 test:watch /home/samuel/Documents/fiware/fiware-idm
> npm run test -- -w ./lib


> fiware-idm@7.9.0 test /home/samuel/Documents/fiware/fiware-idm
> nyc --reporter=text mocha -- --recursive 'test/**/*.js' --reporter spec --timeout 3000 --ui bdd --exit "-w" "./lib"



MySQL is up and running
----------------------|---------|----------|---------|---------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
File                  | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s                                                                                                                                                     
----------------------|---------|----------|---------|---------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
All files             |   20.95 |    13.03 |    7.32 |    20.9 |                                                                                                                                                                       
 fiware-idm           |     100 |      100 |     100 |     100 |                                                                                                                                                                       
  config.js           |     100 |      100 |     100 |     100 |                                                                                                                                                                       
 fiware-idm/lib       |   19.37 |    12.69 |    7.32 |   19.31 |                                                                                                                                                                       
  authzforce.js       |   11.76 |        0 |       0 |   11.76 | 14-219,228-250                                                                                                                                                        
  configService.js    |   38.71 |    33.51 |      60 |   38.71 | ...67,174-187,193,196,199,204-207,213,219,222,227-228,234-259,266,269,272,275,278,281,286-287,298,303-309,316-322,329,338,341,344,349-385,392,395,398,404,407,413-422 
  database.js         |    9.62 |        0 |       0 |    9.62 | 14-100                                                                                                                                                                
  email.js            |   38.46 |        0 |       0 |   38.46 | 8-27                                                                                                                                                                  
  image.js            |   24.07 |        0 |       0 |   24.07 | 11-17,23-31,39-52,61-71,76-86,92-97                                                                                                                                   
  mailer.js           |   51.72 |       25 |   33.33 |   51.72 | 13-16,25,38-57                                                                                                                                                        
  object_functions.js |      20 |        0 |       0 |      20 | 3-7,13-17                                                                                                                                                             
  ptp.js              |   14.89 |        0 |       0 |   15.22 | 15-99                                                                                                                                                                 
  saml2.js            |   12.34 |     0.83 |    6.33 |   12.19 | ...43,864-900,905-938,972-1023,1040-1187,1203-1220,1224,1229-1249,1265-1300,1310-1325,1329-1338,1342-1351,1359-1457,1468-1513,1521-1554,1562-1576,1584-1590,1597-1613 
  sequelize.js        |     100 |      100 |     100 |     100 |                                                                                                                                                                       
  time.js             |   11.11 |        0 |       0 |   11.11 | 4-13                                                                                                                                                                  
----------------------|---------|----------|---------|---------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
```
no tests and no data gets loaded into the database. The database `idm_test` doesn't get deleted after.

**Comment by apozohue10** [comment]
mmmm It seems that there is a bug (which is not related with your PR) that I should check carefully. Anyways, all checks are passing and I see that you have changed the stuff that we have commented. 

So, I will check this bug next week and accept the PR.

Thank you again for your contribution!

**Comment by SamuelTJackson** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by SamuelTJackson** [comment]
recheckcla

**Comment by SamuelTJackson** [comment]
@apozohue10  
Hey, 
do you want to merge this pr or do you want me to change something?

**Comment by apozohue10** [comment]
Sorry again for the delay. I will merge to include in this release.

It seems that the check of the CLA is failing. I guess that the failure is because you make a commit after signing the CLA. Could you re-sing the CLA? 

Thank you and sorry again for the delay

**Comment by SamuelTJackson** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by SamuelTJackson** [comment]
recheckcla

**Pull request merged**
