### PR TITLE
Fix #93 - Update Docker documentation

### LINKED ISSUE #93: Docker container does not create the database
Hello,
if I try to run the IdM service with docker compose it does not work.
Specifically, it creates 2 containers (mysql and idm) but, if I look at the the IdM container logs I find a lot of this messages:
```
waiting for database connection
```
After investigating about the issues, I found the problem: the database is not completely created. If I execute a `show databases` in the mysql container I obtain only 4 databases:
* information_schema
* mysql
* performance_schema
* sys

(I partially solved the problem by using a (maybe, because there is no connection among the 2 repositories) newer version of the Idm, and specifically by following this tutorial:
[FIWARE/tutorials.Identity-Management](https://github.com/FIWARE/tutorials.Identity-Management)
)

### PR DESCRIPTION
**Pull request by jason-fox**
* Update Docker compose version
* Update `IDM_DB_HOST` ENV Parameter to work with 7.6
* Include SQL Database in example
* Highlight insecure use of sensitive data
* Add `console` highlighting for GitHub

### CODE REVIEW

**Comment by tmontanaro** [comment]
I think you should also update the sample code reported in the last part of the README (in "Other features")

**Comment by tmontanaro** [comment]
Resolves: #93

**Comment by tmontanaro** [comment]
Resolves #94

**Comment by apozohue10** [comment]
Thank you Jason!!

**Pull request merged**
